### ISSUE TITLE
Issue #02 - MVP List

### ISSUE THREAD

**Issue by keginzburg** [KevinTungDHR/Relay#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
Your schedule meets 12 days while you have a full 14 days available. Do you think you can get your 7 MVPs done in the shorter time frame?

1. Splash Page/User Authentication
    1. I would specify that these go together as the splash page will be what every user sees before authentication. Additionally, I would separate account deletion into a separate bonus MVP (Account) where you could integrate update functionality as well.
    2. Also, I would add a Demo Login feature in this MVP.
2. Main Page/Workspaces
    1. I would specify that adding a new workspace is functionality, but the other bullets are more styling issues and CSS related.
    2. I would incorporate your Live Chat/Websockets MVP here instead. Websockets will be the toughest part of this project, so they should be on their own as an MVP.
3. Channels
    1. This alone is a full MVP that has CRUD and utilizes the previous Live Chat MVP.
4. Direct Message
    1. I would specify that DMs utilize live chat as well.
5. Bonuses
    1. Not a big deal, but I would add more detail for these. Just a suggestion.

**Comment by KevinTungDHR** [comment]
I've updated my MVP List to reflect your comments. 

*  I've front-loaded two extra days (1 for User Auth and 1 for Websockets) for a total of 14 days.
*  Combined Splash Page and User Auth
*  Added Demo Login as a feature and moved account deletion to a bonus
*  Made Live Chat/Websockets and Workspaces (What I perceive as action cable channels) into one category
*  Channels moved to it's own MVP
*  Added details to DM and Group Chat
*  Added details to bonuses
