### ISSUE TITLE
Issue #04 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [KevinTungDHR/Relay#4]
# Sample State
- [X] State shape is flat!
- [X] State’s keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
In your workspace slice of state, you have the owner pointing to an email string. Should it point to the user’s primary key id instead (to reflect the integer data type and foreign key in your database schema)?

**Comment by KevinTungDHR** [comment]
Updates:

*  Pointed the ownerId of a workspace to the user primary key instead of an email
*  Updated my direct chat slice of state and subscriptions slice of state to reflect the changes in my database schema
*  Corrected some typos regarded snake_cased keys when they should be camelCased
