### ISSUE TITLE
Issue #06 - Frontend Routes & Components

### ISSUE THREAD

**Issue by keginzburg** [KevinTungDHR/Relay#6]
# Frontend Routes
- [X] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
I see how you are planning to separate by workspaces and their ids in your paths, but I need a better grasp of how you plan to design the component structure in this section.

Also, should the user_profile/:user_id path live outside of the workspaces? Can a single profile log into multiple workspaces? Or will profiles be separated by workspaces?

Definitely utilize [Bluebird Frontend Routes & Components](https://github.com/appacademy/bluebird/wiki/frontend-routes) for a general idea of how to structure this section between frontend routes and their components.

**Comment by KevinTungDHR** [comment]
I've updated my frontend routes with components, descriptions and formatting to better outline how I believe the frontend routes should be designed.
Following Slack's design, profiles will be separated by workspaces but profiles at this point are a bonus.

**Comment by keginzburg** [comment]
Everything looks solid. Interested to see how you implement the workspaces with the design you have.
